import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  handbookSidebar: [
    'intro',
    'roadmap',
    {
      type: 'category',
      label: '📚 Volume 1 — Foundations',
      collapsed: false,
      items: [
        'fundamentals/ai-landscape',
        'fundamentals/ai-terminology',
        'fundamentals/llm-basics',
        'fundamentals/tokens-and-context',
        'fundamentals/prompt-engineering',
        'fundamentals/embeddings-intro',
        'fundamentals/transformer-overview',
        'fundamentals/ai-system-design-overview',
      ],
    },
    {
      type: 'category',
      label: '🧠 Volume 2 — LLM Engineering',
      collapsed: true,
      items: [
        'llm-engineering/transformer-architecture',
        'llm-engineering/self-attention',
        'llm-engineering/tokenization-internals',
        'llm-engineering/embedding-models',
        'llm-engineering/cosine-similarity',
        'llm-engineering/finetuning-vs-rag',
        'llm-engineering/advanced-embedding-strategies',
        'llm-engineering/vector-databases-deep-dive',
        'llm-engineering/indexing-hnsw',
        'llm-engineering/hallucinations-and-mitigation',
        'llm-engineering/production-rag-systems',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Volume 3 — .NET AI Integration',
      collapsed: true,
      items: [
        'dotnet-ai/openai-sdk',
        'dotnet-ai/azure-openai',
        'dotnet-ai/semantic-kernel-basics',
        'dotnet-ai/microsoft-extensions-ai',
        'dotnet-ai/aspnet-core-ai-patterns',
        'dotnet-ai/building-ai-apis',
        'dotnet-ai/streaming-with-signalr',
        'dotnet-ai/background-ai-processing',
        'dotnet-ai/dependency-injection-patterns',
        'dotnet-ai/rag-architecture-dotnet',
        'dotnet-ai/vector-databases-dotnet',
        'dotnet-ai/local-models-ollama',
      ],
    },
    {
      type: 'category',
      label: '🏗️ Volume 4 — Architecture Patterns',
      collapsed: true,
      items: [
        'architecture/ai-architecture-principles',
        'architecture/enterprise-ai-patterns',
        'architecture/agent-architectures',
        'architecture/event-driven-ai',
        'architecture/ai-microservices',
        'architecture/multi-agent-systems',
        'architecture/security-and-governance',
        'architecture/observability',
      ],
    },
    {
      type: 'category',
      label: '🧪 Volume 5 — Labs',
      collapsed: true,
      items: [
        'labs/simple-llm-api',
        'labs/prompt-engineering',
        'labs/mini-rag-system',
        'labs/local-ai-ollama',
        'labs/semantic-kernel-agent',
      ],
    },
    {
      type: 'category',
      label: '🏭 Volume 6 — FactoryMind',
      collapsed: true,
      items: [
        'factorymind/system-architecture-design',
        'factorymind/backend-services',
        'factorymind/ai-orchestration-layer',
        'factorymind/event-driven-architecture',
        'factorymind/messaging-kafka-rabbitmq',
        'factorymind/multi-agent-workflow',
      ],
    },
    {
      type: 'category',
      label: '🎓 Certifications',
      collapsed: true,
      items: [
        'certifications/ai-900',
      ],
    },
  ],
};

export default sidebars;
